name: Metrics
on:
  schedule: [{cron: "0 */1 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          base: ""
          plugin_isocalendar: yes
          plugin_gists: yes
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          
          plugin_repositories: yes
          plugin_repositories_pinned: 2
          
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
